version: '3'

services:

  consul-agent-1: &consul-agent
    image: consul:latest
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:8600"
    - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

  app-a:
    image: yokv/app-a
    extra_hosts:
    - dev.aiyo.space:192.168.66.131

  app-b:
    image: yokv/app-b
    extra_hosts:
    - dev.aiyo.space:192.168.66.131

  app-c:
    image: yokv/app-c

    extra_hosts:
    - dev.aiyo.space:192.168.66.131

  gateway:
    image: yokv/gateway
    ports:
    - 80:80
    extra_hosts:
    - dev.aiyo.space:192.168.66.131

  hystrix-dashboard:
    image: yokv/hystrix-dashboard
    ports:
    - 9090:9090
    extra_hosts:
    - dev.aiyo.space:192.168.66.131

  admin:
    image: yokv/admin
    ports:
    - 9100:9100
    extra_hosts:
    - dev.aiyo.space:192.168.66.131

  zipkin:
    image: openzipkin/zipkin
    environment:
    - STORAGE_TYPE=mem
    ports:
    - 9411:9411

  prometheus:
    image: prom/prometheus
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - 9099:9090
    extra_hosts:
    - dev.aiyo.space:192.168.66.131

  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    depends_on:
    - prometheus
    extra_hosts:
    - dev.aiyo.space:192.168.66.131