eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: app-reactive
  redis:
    host: localhost
    port: 6379
    password: redisPwd
    database: 8
    lettuce:
      shutdown-timeout: 1000ms
      pool:
        max-active: 10
        max-wait: -1s
        max-idle: 10
        min-idle: 1
server:
  port: 8808