spring:
  application:
    name: server-eureka

---
server:
  port: 8761
spring:
  profiles: peer1
eureka:
  instance:
    hostname: server-eureka-peer1
  client:
    serviceUrl:
      defaultZone: http://server-eureka-peer2:8762/eureka/

---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    hostname: server-eureka-peer2
  client:
    serviceUrl:
      defaultZone: http://server-eureka-peer1:8761/eureka/

---
server:
  port: 8761
spring:
  profiles: default
eureka:
  instance:
    hostname: server-eureka
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false